on: [push]
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/c-utils-tools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      - name: Generate CMake cache
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        run: cmake -B build -G Ninja
      - name: Cppcheck
        working-directory: ./build
        run: cmake --build . --target cppcheck
      - name: Upload Cppcheck Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-report
          path: libutils/build/cppcheck_report.xml
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/c-utils-tools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      - name: Generate CMake cache
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        run: cmake -B build -G Ninja
      - name: Build tests
        working-directory: ./build
        run: cmake --build . -j$(nproc)
      - name: Execute tests
        run: ctest --test-dir build --verbose
      - name: Upload unit tests log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-log
          path: libutils/build/Testing/Temporary/LastTest.log
      - name: Upload DoublyLinkedList valgrind report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test_DoublyLinkedList-valgrind-report
          path: libutils/build/test_DoublyLinkedList-valgrind-report.xml
      - name: Upload SinglyLinkedList valgrind report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test_SinglyLinkedList-valgrind-report
          path: libutils/build/test_SinglyLinkedList-valgrind-report.xml
      - name: Upload Queue valgrind report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test_Queue-valgrind-report
          path: libutils/build/test_Queue-valgrind-report.xml
