on: [push]
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/c-utils-tools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        name: Make build directory
        run: mkdir build
      - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        name: Generate CMake cache
        working-directory: ./build
        run: cmake ..
      - name: Cppcheck
        working-directory: ./build
        run: cmake --build . --target cppcheck
      - name: Upload Cppcheck Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-report
          path: libutils/build/cppcheck_report.xml
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/c-utils-tools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        name: Make build directory
        run: mkdir build
      - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        name: Generate CMake cache
        working-directory: ./build
        run: cmake ..
      - name: Build tests
        working-directory: ./build
        run: cmake --build . --target test_DoublyLinkedList test_SinglyLinkedList test_Queue
      - name: Test DoublyLinkedList
        working-directory: ./build
        run: ./LinkedList/test_DoublyLinkedList
      - name: Test SinglyLinkedList
        working-directory: ./build
        run: ./LinkedList/test_SinglyLinkedList
      - name: Test Queue
        working-directory: ./build
        run: ./Queue/test_Queue
