on: [push]
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/c-utils-tools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      - name: Make build directory
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        run: mkdir build
      - name: Generate CMake cache
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        working-directory: ./build
        run: cmake ..
      - name: Cppcheck
        working-directory: ./build
        run: cmake --build . --target cppcheck
      - name: Upload Cppcheck Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-report
          path: libutils/build/cppcheck_report.xml
  unit-tests-and-valgrind:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/c-utils-tools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', '**.cmake') }}
      - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        name: Make build directory
        run: mkdir build
      - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        name: Generate CMake cache
        working-directory: ./build
        run: cmake ..
      - name: Build tests
        working-directory: ./build
        run: cmake --build . --target test_DoublyLinkedList test_SinglyLinkedList test_Queue
      - name: Test DoublyLinkedList
        working-directory: ./build/LinkedList
        run: valgrind --leak-check=full --error-exitcode=2 --xml=yes --xml-file=test_DoublyLinkedList-valgrind-report.xml -s ./test_DoublyLinkedList > test_DoublyLinkedList-unit_tests-report.txt
      - name: Upload DoublyLinkedList unit test report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test_DoublyLinkedList-unit_tests-report
          path: libutils/build/test_DoublyLinkedList-unit_tests-report.txt
      - name: Upload DoublyLinkedList valgrind report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test_DoublyLinkedList-valgrind-report
          path: libutils/build/test_DoublyLinkedList-valgrind-report.xml
      - name: Test SinglyLinkedList
        working-directory: ./build/LinkedList
        run: valgrind --leak-check=full --error-exitcode=2 --xml=yes --xml-file=test_SinglyLinkedList-valgrind-report.xml -s ./test_SinglyLinkedList > test_SinglyLinkedList-unit_tests-report.txt
      - name: Upload SinglyLinkedList unit test report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test_SinglyLinkedList-unit_tests-report
          path: libutils/build/test_SinglyLinkedList-unit_tests-report.txt
      - name: Upload SinglyLinkedList valgrind report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test_SinglyLinkedList-valgrind-report
          path: libutils/build/test_SinglyLinkedList-valgrind-report.xml
      - name: Test Queue
        working-directory: ./build/Queue
        run: valgrind --leak-check=full --error-exitcode=2 --xml=yes --xml-file=test_Queue-valgrind-report.xml -s ./test_Queue > test_Queue-unit_tests-report.txt
      - name: Upload Queue unit test report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test_Queue-unit_tests-report
          path: libutils/build/test_Queue-unit_tests-report.txt
      - name: Upload Queue valgrind report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test_Queue-valgrind-report
          path: libutils/build/test_Queue-valgrind-report.xml
